sudo: false
language: python

python:
  - "2.7"
  - "3.6"

env:
  - TORCH_VERSION=1.0.1
  - TORCH_VERSION=0.4.1
#  - TORCH_VERSION=0.3.1  # giving up on this

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n testenv python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - conda install -c pytorch pytorch-cpu=$TORCH_VERSION numpy scipy scikit-learn pytest cython
  - pip install sklearn-contrib-lightning
  # install package
  - cd pytorch
  - pip install .

script:
  - mkdir empty_dir
  - pytest pytest -vs --pyargs torchsparseattn
  - cd .. 
